{811}{966}'The best way to eat natto fermented beans.
{970}{1005}'You need good beans...
{1009}{1045}'and to do it right.
{1048}{1083}'First you take your chopsticks...
{1087}{1130}'...and you mash 'em up good'
{1196}{1231}What are you doing, Norimichi?.
{1235}{1254}What?.
{1257}{1311}It's a school day. You'll be late.
{1314}{1375}I know. I'm going right now.
{1473}{1537}--Hey, that's cold!|--Get going!
